abecedario = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
abecedario = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
abecedario = 'abcdefghijklmnopqrstuvwxyz'
abecedario = 'ABCDEFGHiJKLMNOPQRSTUVWXYZ'
abecedario = ['A','B', 'C', ' ','D', 'E', 'F', ' ','G', 'H', 'I', ' ', 'J', 'K', 'L', ' ', 'M', , 'N', 'O', ' ', 'P', 'Q', 'R', ' ', 'S', 'T', 'U', ' ','V', 'W', 'X', ' ','Y', 'Z', 'ZZ']
